global:
  scrape_interval:     15s
  external_labels:
      host: 'deployer.datahighway.com'

scrape_configs:
  - job_name: 'dhx-deployer'
    static_configs:
      - targets: ['nodeexporter:9100','cadvisor:8080']

